DTO_TYPE = "func"
name = "test"

[globals]
DTO_TYPE = "dict"
glob = 2

[code]
DTO_TYPE = "code"

[code.fields]
DTO_TYPE = "dict"
co_argcount = 1
co_cellvars = []
co_code = "64017400170064011700640114005300"
co_filename = "/home/dkefir03/labs/ISP-2022-053504/main.py"
co_firstlineno = 29
co_flags = 67
co_freevars = []
co_kwonlyargcount = 0
co_lnotab = "0004"
co_name = "test"
co_nlocals = 1
co_posonlyargcount = 0
co_stacksize = 2

[code.fields.co_consts]
DTO_TYPE = "list"
__dto__list_dict_item0 = {}
__dto__list_dict_item1 = 2

[code.fields.co_names]
DTO_TYPE = "list"
__dto__list_dict_item0 = "glob"

[code.fields.co_varnames]
DTO_TYPE = "list"
__dto__list_dict_item0 = "arg1"

