DTO_TYPE = "func"
name = "test"

[globals]
DTO_TYPE = "dict"
from_val = 228
glob = 2

[globals.mod_test]
DTO_TYPE = "module"
name = "mod_test"

[globals.mod_test.fields]
DTO_TYPE = "dict"
from_val = 228
glob = 16

[globals.mod_test.fields.from_module]
DTO_TYPE = "func"
name = "from_module"

[globals.mod_test.fields.from_module.globals]
DTO_TYPE = "dict"

[globals.mod_test.fields.from_module.code]
DTO_TYPE = "dict"
co_argcount = 1
co_cellvars = []
co_code = "74007c00640117008301010064005300"
co_consts = [{}," ya"]
co_filename = "/home/dkefir03/labs/ISP-2022-053504/mod_test.py"
co_firstlineno = 1
co_flags = 67
co_freevars = []
co_kwonlyargcount = 0
co_lnotab = "0001"
co_name = "from_module"
co_names = ["print"]
co_nlocals = 1
co_posonlyargcount = 0
co_stacksize = 3
co_varnames = ["msg"]



[code]
DTO_TYPE = "dict"
co_argcount = 1
co_cellvars = []
co_code = "74006a017d0164017402170064011700640114005300"
co_consts = [{},2]
co_filename = "/home/dkefir03/labs/ISP-2022-053504/main.py"
co_firstlineno = 21
co_flags = 67
co_freevars = []
co_kwonlyargcount = 0
co_lnotab = "00010602"
co_name = "test"
co_names = ["mod_test","from_val","glob"]
co_nlocals = 2
co_posonlyargcount = 0
co_stacksize = 2
co_varnames = ["arg1","a"]

